[package]
name = "steam-docker-updater"
version = "0.1.0"
authors = ["Laura Demkowicz-Duffy <laura@laurademkowiczduffy.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
